### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by cbh34680** [podhmo/dictknife#188]
```python
import dictknife

left = {'arr': []}
right = {'arr': [1, 1]}

merge = dictknife.deepmerge(left, right)
print(f'mege = |{merge}|')
```
_mege = |{'arr': [1]}|_

**Comment by podhmo** [comment]
https://github.com/podhmo/dictknife/blob/a172220c1adc8411b69f31646ea2154932d71516/dictknife/deepmerge.py#L84-L87

If it's not what you expect, you can use method options to change it.

**Comment by cbh34680** [comment]
I understand, Thank you
